Change docker repository to store the images we are generating.
gataca-io/gataca.io pull request #336
Opened 2024-11-21 12:32 UTC by samu-gataca

We are changing docker hub to Github Container Registry (ghcr.io)

2024-11-21 12:38 UTC, samu-gataca commented
@mayra-gataca When you finish the current work please do it. Also @navas-gataca should be notified about that.

2024-11-21 12:51 UTC, mayra-gataca requested changes
@samu-gataca some conflicts must be fixed in the following files

web/deployments/deployment-dev.yml
web/deployments/deployment-pro.yml

2024-11-21 12:55 UTC, samu-gataca commented
> @samu-gataca some conflicts must be fixed in the following files
> 
> web/deployments/deployment-dev.yml web/deployments/deployment-pro.yml

Just when it's finished on your side. This will change the registry so @navas-gataca must be notified. See my comment below

2024-11-25 09:56 UTC, mayra-gataca approved these changes

2024-11-25 10:32 UTC, merged